# autogenerated at Mon, 10 Oct 2011 20:53:22 +0200 by configure
BUMBLEBEE_VERSION := 2.4.1~gitdc8b2c6

BINDIR      := /usr/bin
SBINDIR     := /usr/sbin
CONFDIR     := /bumblebee
LIBDIR      := /bumblebee
INITDIR     := /etc/init.d
BUILDDIR    := .build
XORG_MODULEPATH := 

DRIVERS     := nouveau
NVIDIABUSID := 01:00:0
